// Generated by scripts/build-site.js for the static review site.
export const CONFIG = {
    mode: 'static',
    tokenUrl: "",
    publicUrl: "https://gitaecllmdev.github.io/cas-bim-web-viewer/",
    stateUrl: "",
};
